modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="cgm"
version="0.16.2"
displayName="MrCrayfish's Gun Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cgm/update.json"
displayURL="https://mrcrayfish.com/"
authors="MrCrayfish"
description='''
Adds weapons into Minecraft
'''

[[dependencies.cgm]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cgm]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.4.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cgm]]
    modId="controllable"
    mandatory=false
    versionRange="[0.8.1,)"
    ordering="AFTER"
    side="CLIENT"
